image: "${GLOBAL_IMAGE_NAME}:${GLOBAL_IMAGE_TAG}"

# https://gitlab.com/singletonsd/pipelines/angular
include:
  - project: 'singletonsd/pipelines/angular'
    file: '/src/.gitlab-ci-app.yml'

variables:
  GLOBAL_IMAGE_NAME: "node"
  GLOBAL_IMAGE_TAG: "8-alpine"
  TEST_STATIC_ALL: "true"
  ORIGINAL_REPOSITORY: "ravimosharksas/frontends/office"
  AWS_DEPLOY: "false"

stages:
  - install
  - test_static
  - build
  - test_dynamic
  - pre_deploy
  - deploy

build:
  stage: build
  before_script:
    - apk --no-cache add git bash
    - rm -rf dist
  script:
    - npm run build-all ${CI_COMMIT_REF_NAME}
  artifacts:
    name: "$CI_PROJECT_NAME-${CI_COMMIT_REF_NAME}"
    paths:
      - dist/
    expire_in: 20 yrs

deploy-singleton-server:
  image: python:3.7.3-alpine3.10
  stage: deploy
  variables:
    AWS_DEFAULT_REGION: eu-west-3 # The region of S3 bucket
    AWS_ACCESS_KEY_ID: ${AWS_S3_SINGLETON_RAVIMO_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_S3_SINGLETON_RAVIMO_KEY}
  before_script:
    - apk --no-cache add bash lftp
    - export DATE="$(date '+%Y-%m-%d--%H:%M:%S')"
    - pip install awscli # Install the SDK
  script:
    - if [ "${CI_REGISTRY_IMAGE}" == "registry.gitlab.com/ravimosharksas/frontends/office" ]; then
        ./scripts/uploader_amazon_s3.sh ${AWS_S3_BUCKET_SINGLETON_RAVIMO} ${CI_COMMIT_REF_NAME};
      else
        echo "Deploy to server only in ravimoshark pipeline";
      fi
  when: on_success
  only:
    variables:
      - $CI_PROJECT_PATH == $ORIGINAL_REPOSITORY && $AWS_DEPLOY == "true"
