image: "${GLOBAL_IMAGE_NAME}:${GLOBAL_IMAGE_TAG}"

# https://gitlab.com/singletonsd/pipelines/angular
include:
  - project: 'singletonsd/pipelines/angular'
    file: '/src/.gitlab-ci-app.yml'

variables:
  GLOBAL_IMAGE_NAME: "node"
  GLOBAL_IMAGE_TAG: "8-alpine"
  TEST_STATIC_ALL: "true"
  ORIGINAL_REPOSITORY: "ravimosharksas/frontends/office"
  NG_APP_AWS_S3_DEPLOY: "false"
  NG_APP_AWS_S3_REGION: eu-west-3
  NG_APP_AWS_S3_ACCESS_KEY_ID: "${AWS_S3_SINGLETON_RAVIMO_ID}"
  NG_APP_AWS_S3_SECRET_ACCESS_KEY: "${AWS_S3_SINGLETON_RAVIMO_KEY}"

stages:
  - install
  - test_static
  - build
  - test_dynamic
  - pre_deploy
  - deploy

build:
  stage: build
  before_script:
    - apk --no-cache add git bash
    - rm -rf dist
  script:
    - npm run build-all ${CI_COMMIT_REF_NAME}
  artifacts:
    name: "$CI_PROJECT_NAME-${CI_COMMIT_REF_NAME}"
    paths:
      - dist/
    expire_in: 20 yrs

