version: "3.3"

services:
  api:
    image: registry.gitlab.com/ravimosharksas/apis/contract/app-nodejs/${API_BASE:-alpine}:${API_VERSION:-8-alpine-latest}
    environment:
      SWAGGER_URL: http://localhost:4201
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_PORT: ${APP_PORT:-8000}
    ports:
      - "${HOST_PORT:-80}:${APP_PORT:-8000}"
